---
version: '3'

volumes:
  data_mysql_80:

services:
  mysql80:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'foobar'
    ports:
      - "20106:3306"
    volumes:
      - data_mysql_80:/var/lib/mysql
    command: [ "mysqld", "--max-allowed-packet=536870912" ]

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: 'mysql80'
      DB_PREFIX: 'wp_'
      DB_NAME: 'wp_test'
      DB_USER: 'root'
      DB_PASSWORD: 'foobar'
      WP_ENV: 'development'
      WP_HOME: 'http://127.0.0.1:8004'
      ENV_SITE_TITLE: 'Wordpress Application'
      ENV_ADMIN_USER: 'admin'
      ENV_ADMIN_PASSWORD: 'admin@123'
      ENV_ADMIN_URL: 'admin@test.com'
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - mysql80
    links:
      - mysql80

  nginx:
    build:
      context: ./
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "8004:80"
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - app
    links:
      - app